nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando...')
print(f'Seu nome em maiúsculas é {nome.upper()}.')
print(f'Seu nome em minúsculas é {nome.lower()}.')
print('Seu nome tem ao todo {} letras'.format(len(nome) - nome.count(' ')))
separa = nome.split()
print('Seu primeiro nome tem {} letras.'.format(separa[0], len(separa[0])))
print('Seu primeiro nome é {} e ele tem {} letras.'.format(separa[0], len(separa[0])))